
project_id = "ushqcekjondadeqwieke"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true

[functions.verify-provider-access]
verify_jwt = false

[functions.verify-employee-access]
verify_jwt = false

[functions.create-provider-access]
verify_jwt = true
