// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ushqcekjondadeqwieke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzaHFjZWtqb25kYWRlcXdpZWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NTE4MTcsImV4cCI6MjA2NDMyNzgxN30.lU3qJwJkM3fq47KV-LE1rqPMAyzM3aD-YseqC0sIKzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);